# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simplelegal_id', models.CharField(max_length=200)),
                ('invoice_number', models.IntegerField()),
                ('invoice_date', models.DateField()),
                ('status', models.CharField(max_length=200)),
                ('received_date', models.DateField()),
                ('billing_start_date', models.DateField()),
                ('billing_end_date', models.DateField()),
                ('total', models.DecimalField(decimal_places=4, max_digits=12)),
                ('net', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('tax', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('native_currency', models.CharField(max_length=3, null=True)),
                ('native_total', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('native_net', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('native_tax', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('approvers', models.CharField(max_length=200)),
                ('vendor', models.CharField(max_length=200)),
                ('vendor_id', models.CharField(max_length=200)),
                ('api_url', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
