# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplelegal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_item_number', models.IntegerField()),
                ('invoice_number', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('law_firm_matter_id', models.CharField(max_length=200)),
                ('client_id', models.IntegerField()),
                ('line_item_type', models.CharField(max_length=200)),
                ('units', models.DecimalField(decimal_places=4, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('adjustment', models.DecimalField(decimal_places=4, max_digits=12)),
                ('total', models.DecimalField(decimal_places=4, max_digits=12)),
                ('date', models.DateTimeField()),
                ('task_code', models.CharField(max_length=200, null=True)),
                ('expense_code', models.CharField(max_length=200, null=True)),
                ('activity_code', models.CharField(max_length=200, null=True)),
                ('timekeeper_id', models.CharField(max_length=200, null=True)),
                ('timekeeper', models.CharField(max_length=200, null=True)),
                ('timekeeper_level', models.CharField(max_length=200, null=True)),
                ('native_tax', models.DecimalField(decimal_places=4, max_digits=12)),
                ('native_rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('native_adjustment', models.DecimalField(decimal_places=4, max_digits=12)),
                ('native_total', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
        ),
    ]
